### PR TITLE
Add metadata for Nodle crowdloan

### PR DESCRIPTION
**Pull request by noisefloors**
Data:

```
{   "ParaID": 2026,   "Project Name": "Nodle",   "Logo": "../../assets/images/nodle.svg",   "Description (en)": "Nodle is a decentralized wireless network, harnessing the power of smartphones to provide a low-cost and secure IoT infrastructure for enterprises, device manufacturers, and smart cities.",   "Description (zh)": "",   "Parachain Crowdloans Allocation (en)": "https://parachain.nodle.com",   "Parachain Crowdloans Allocation (zh)": "",   "Auction Reward & Reward Vesting Schedule (en)": "https://learn.nodleprotocol.io/parachain/crowdloan",   "Auction Reward & Reward Vesting Schedule (zh)": "",   "Financing Information (en)": "",   "Financing Information (zh)": "",   "Website Link": "https://nodle.com/",   "Twitter Link": "https://twitter.com/NodleNetwork",   "Telegram Link": "https://t.me/NodleCommunity",   "Discord Link": "https://discord.gg/N5nTUt8RWJ",   "Medium Link": "https://medium.com/@Nodle",   "Github Link": "https://github.com/NodleCode",   "Owner account": "16LKv69ct6xDzSiUjuz154vCg62dkyysektHFCeJe85xb6X" }
```

Owner account:
```
16LKv69ct6xDzSiUjuz154vCg62dkyysektHFCeJe85xb6X
```

Signature:

```
0x887db7884b4933bf13186fd3bfdc7e30914a57b804300d1f0a8ef167b84a566206196a9dbe1eca97505a866c120337a84f854dd8a64a89b529322e13754d1e81
```

### CODE REVIEW

**Review by carlhong — CHANGES_REQUESTED** [review]
Please add a description for your pr, the description includes the original data of the signature, signature account, and signature.

**Comment by noisefloors** [comment]
@carlhong I reformatted the  description. Hopefully this is correct.

**Comment by carlhong** [comment]
@noisefloors Verify failed. I'm using the data in the description to verify. Please recheck it.
image

**Comment by noisefloors** [comment]
> @noisefloors Verify failed. I'm using the data in the description to verify. Please recheck it. image

Updated to use the reformatted version directly from Polkadot.js.

**Comment by carlhong** [comment]
image
Verified!

**Review by carlhong — APPROVED** [review]

**Comment by noisefloors** [comment]
Thanks for your patience and support by listing the crowdloan. 💯

**Comment by IGhottem** [comment]
Going into reward rules this page link is broken

**Pull request merged**
