### PR TITLE
Add KILT Protocol info

### PR DESCRIPTION
**Pull request by weichweich**
# Kusama:

```
{"Para ID":"2005","Project Name":"KILT Protocol","Logo":"../../assets/images/kilt.svg","Description (en)":"KILT is a blockchain protocol for issuing self-sovereign verifiable, revocable credentials in the Web 3.0.","Parachain Crowdloans Allocation (en)":"","Parachain Crowdloans Allocation (zh)":"","Auction Reward & Reward Vesting Schedule (en)":"","Auction Reward & Reward Vesting Schedule (zh)":"","Financing Information (en)":"","Financing Information (zh)":"","Website Link":"https://www.kilt.io/","Twitter Link":"https://twitter.com/Kiltprotocol","Telegram Link":"https://t.me/KILTProtocolChat","Discord Link":"","Medium Link":"https://kilt-protocol.medium.com/","Github Link":"https://github.com/KILTprotocol","Owner account":"GqVWENYQDEcz2UFDj7saV5nyDEvDH1QNCQE5QrjQR4XgFcw"}
```

# Account:

`GqVWENYQDEcz2UFDj7saV5nyDEvDH1QNCQE5QrjQR4XgFcw`

# Signature:

`0x108ff93923f27f2bbad29bbf82407f8859ed3406f57fc3303d25ba71af7aa8796e469bd5fc9bb6aad036a7f04ad5f7813687a27d0a3a94426cdce6747804bb85`

### CODE REVIEW

**Comment by yakio** [comment]
image
The signature verification failed, please check the correctness of the data format and content

**Comment by yakio** [comment]
> # Kusama:
> ```
> {
>         "Para ID": "2005",
>         "Project Name": "KILT Protocol",
>         "Logo": "../../assets/images/kilt.svg",
>         "Description (en)": "KILT is a blockchain protocol for issuing self-sovereign verifiable, revocable credentials in the Web 3.0.",
>         "Parachain Crowdloans Allocation (en)": "",
>         "Parachain Crowdloans Allocation (zh)": "",
>         "Auction Reward & Reward Vesting Schedule (en)": "",
>         "Auction Reward & Reward Vesting Schedule (zh)": "",
>         "Financing Information (en)": "",
>         "Financing Information (zh)": "",
>         "Website Link": "https://www.kilt.io/",
>         "Twitter Link": "https://twitter.com/Kiltprotocol",
>         "Telegram Link": "https://t.me/KILTProtocolChat",
>         "Discord Link": "",
>         "Medium Link": "https://kilt-protocol.medium.com/",
>         "Github Link": "https://github.com/KILTprotocol",
>         "Owner account": "GqVWENYQDEcz2UFDj7saV5nyDEvDH1QNCQE5QrjQR4XgFcw"
>     }
> ```
> 
> # Account:
> `GqVWENYQDEcz2UFDj7saV5nyDEvDH1QNCQE5QrjQR4XgFcw`
> 
> # Signature:
> `0x108ff93923f27f2bbad29bbf82407f8859ed3406f57fc3303d25ba71af7aa8796e469bd5fc9bb6aad036a7f04ad5f7813687a27d0a3a94426cdce6747804bb85`

The signature verification failed, please check the correctness of the data format and content

**Comment by weichweich** [comment]
> The signature verification failed, please check the correctness of the data format and content
> 
> image

Yeah just noticed that we used the minified json. 🤦🏻 Sorry for that.

**Comment by carlhong** [comment]
截屏2021-07-14 上午9 49 29

**Pull request merged**
